Add-Type -AssemblyName PresentationFramework

$dataDirectory = Join-Path $env:APPDATA 'AI Software Team'
$dataFile = Join-Path $dataDirectory 'workspace.json'
$script:sessionApiKey = ''
$script:events = [System.Collections.Generic.List[string]]::new()
$script:events.Add('Windows 桌面客户端已启动')
$script:events.Add('指挥 Agent 已就绪，等待任务进入队列')
$script:agents = @('产品经理 Agent','架构师 Agent','技术主管 Agent','前端 Agent','后端 Agent','测试 Agent','安全专家 Agent','DevOps Agent')
$script:skills = [ordered]@{
  '指挥 Agent'=@('任务分解','Agent 路由','结果汇总'); '产品经理 Agent'=@('需求分析','PRD 生成','优先级规划'); '架构师 Agent'=@('架构设计','技术选型','接口契约'); '技术主管 Agent'=@('代码评审','实施规划','风险识别'); '前端 Agent'=@('界面实现','组件设计','体验验证'); '后端 Agent'=@('API 设计','数据建模','服务集成'); '测试 Agent'=@('测试设计','自动化测试','质量报告'); '安全专家 Agent'=@('威胁建模','依赖审查','安全验收'); 'DevOps Agent'=@('构建流水线','部署编排','运行监控')
}

function New-TaskItem($title, $agent, $priority, $status, $description) { [pscustomobject]@{ Title=$title; Agent=$agent; Priority=$priority; Status=$status; Description=$description } }
function Get-DefaultTasks { @(
  (New-TaskItem '梳理 MVP 用户需求' '产品经理 Agent' '高' '待处理' '明确首批用户场景和验收条件。'),
  (New-TaskItem '定义任务编排领域模型' '架构师 Agent' '高' '进行中' '建立任务、Agent 与执行记录的基础契约。'),
  (New-TaskItem '创建项目工作台原型' '前端 Agent' '中' '已完成' '完成任务流与 Agent 分派界面。')
) }
try { $saved = Get-Content $dataFile -Raw | ConvertFrom-Json; $script:tasks = [System.Collections.ArrayList]@($saved) } catch { $script:tasks = [System.Collections.ArrayList]@(Get-DefaultTasks) }

[xml]$xaml = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="AI Software Team" Height="760" Width="1180" MinHeight="650" MinWidth="980" WindowStartupLocation="CenterScreen" Background="#F4F7F8">
 <Grid><Grid.ColumnDefinitions><ColumnDefinition Width="220"/><ColumnDefinition Width="*"/></Grid.ColumnDefinitions>
  <Border Grid.Column="0" Background="#152B3B"><DockPanel Margin="14"><StackPanel DockPanel.Dock="Top"><TextBlock Text="AI&#x0a;Software Team" Foreground="White" FontSize="20" FontWeight="Bold" Margin="10,14,10,28"/><Button Name="ProjectsNav" Content="项目工作台" Style="{StaticResource {x:Static ToolBar.ButtonStyleKey}}" Foreground="#DCEBF1" HorizontalContentAlignment="Left" Padding="10"/><Button Name="OrchestratorNav" Content="智能调度中心" Style="{StaticResource {x:Static ToolBar.ButtonStyleKey}}" Foreground="#DCEBF1" HorizontalContentAlignment="Left" Padding="10"/><Button Name="SettingsNav" Content="模型与 API" Style="{StaticResource {x:Static ToolBar.ButtonStyleKey}}" Foreground="#DCEBF1" HorizontalContentAlignment="Left" Padding="10"/><Button Name="SkillsNav" Content="技能中心" Style="{StaticResource {x:Static ToolBar.ButtonStyleKey}}" Foreground="#DCEBF1" HorizontalContentAlignment="Left" Padding="10"/></StackPanel><TextBlock DockPanel.Dock="Bottom" Text="● 指挥 Agent 在线" Foreground="#70D4C7" Margin="10,18"/></DockPanel></Border>
  <Grid Grid.Column="1" Margin="30"><Grid Name="ProjectsPage"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/></Grid.RowDefinitions><DockPanel><StackPanel><TextBlock Text="AI 项目经理" Foreground="#0C827A" FontSize="12"/><TextBlock Text="项目工作台" FontSize="26" FontWeight="Bold" Foreground="#17212B"/></StackPanel><Button Name="NewTask" DockPanel.Dock="Right" Content="新建任务" Background="#1269C7" Foreground="White" Padding="14,8" Margin="0,8"/></DockPanel><Border Grid.Row="1" Background="White" BorderBrush="#D8E0E5" BorderThickness="1" Padding="18" Margin="0,22,0,18"><StackPanel><TextBlock Text="AI Software Team 平台" FontSize="15" FontWeight="Bold"/><TextBlock Text="从需求分析到部署交付的多 Agent 软件研发流程。" Foreground="#637181" Margin="0,7,0,0"/><TextBlock Name="Metrics" Foreground="#405766" Margin="0,12,0,0"/></StackPanel></Border><Grid Grid.Row="2"><Grid.ColumnDefinitions><ColumnDefinition/><ColumnDefinition/><ColumnDefinition/></Grid.ColumnDefinitions><GroupBox Header="待处理" Margin="0,0,10,0"><ListBox Name="TodoList" DisplayMemberPath="Title"/></GroupBox><GroupBox Grid.Column="1" Header="进行中" Margin="0,0,10,0"><DockPanel><StackPanel DockPanel.Dock="Bottom" Orientation="Horizontal" HorizontalAlignment="Right"><Button Name="ProgressBack" Content="上一步" Margin="4"/><Button Name="ProgressNext" Content="下一步" Margin="4"/></StackPanel><ListBox Name="ProgressList" DisplayMemberPath="Title"/></DockPanel></GroupBox><GroupBox Grid.Column="2" Header="已完成"><DockPanel><Button Name="DoneBack" DockPanel.Dock="Bottom" Content="上一步" HorizontalAlignment="Left" Margin="4"/><ListBox Name="DoneList" DisplayMemberPath="Title"/></DockPanel></GroupBox></Grid></Grid>
   <Grid Name="OrchestratorPage" Visibility="Collapsed"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="180"/></Grid.RowDefinitions><DockPanel><StackPanel><TextBlock Text="Agent Orchestrator" Foreground="#0C827A" FontSize="12"/><TextBlock Text="智能调度中心" FontSize="26" FontWeight="Bold" Foreground="#17212B"/></StackPanel><Button Name="RunQueue" DockPanel.Dock="Right" Content="运行下一任务" Background="#1269C7" Foreground="White" Padding="14,8" Margin="0,8"/></DockPanel><Grid Grid.Row="1" Margin="0,22,0,16"><Grid.ColumnDefinitions><ColumnDefinition Width="1.15*"/><ColumnDefinition Width="0.85*"/></Grid.ColumnDefinitions><GroupBox Header="任务执行队列" Margin="0,0,10,0"><ListBox Name="QueueList" DisplayMemberPath="Title"/></GroupBox><GroupBox Grid.Column="1" Header="专业 Agent 注册表"><ListBox Name="AgentList"/></GroupBox></Grid><GroupBox Grid.Row="2" Header="调度事件"><ListBox Name="EventList"/></GroupBox></Grid>
   <Grid Name="SettingsPage" Visibility="Collapsed"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/></Grid.RowDefinitions><StackPanel><TextBlock Text="Model Layer" Foreground="#0C827A" FontSize="12"/><TextBlock Text="模型与 API 配置" FontSize="26" FontWeight="Bold" Foreground="#17212B"/></StackPanel><Border Grid.Row="1" Background="White" BorderBrush="#D8E0E5" BorderThickness="1" Padding="22" Margin="0,22,0,0"><Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/></Grid.RowDefinitions><Grid.ColumnDefinitions><ColumnDefinition Width="150"/><ColumnDefinition Width="420"/></Grid.ColumnDefinitions><TextBlock Grid.ColumnSpan="2" Text="主模型连接" FontSize="15" FontWeight="Bold" Margin="0,0,0,14"/><TextBlock Grid.Row="1" Text="模型提供商" VerticalAlignment="Center"/><ComboBox Name="Provider" Grid.Row="1" Grid.Column="1" SelectedIndex="0"><ComboBoxItem Content="OpenAI"/><ComboBoxItem Content="Anthropic"/><ComboBoxItem Content="Google AI"/><ComboBoxItem Content="DeepSeek"/><ComboBoxItem Content="兼容 OpenAI 的自定义服务"/></ComboBox><TextBlock Grid.Row="2" Text="API Base URL" VerticalAlignment="Center"/><TextBox Name="BaseUrl" Grid.Row="2" Grid.Column="1" Text="https://api.openai.com/v1"/><TextBlock Grid.Row="3" Text="模型名称" VerticalAlignment="Center"/><TextBox Name="ModelName" Grid.Row="3" Grid.Column="1" Text="gpt-4.1-mini"/><TextBlock Grid.Row="4" Text="API Key（本次运行）" VerticalAlignment="Center"/><PasswordBox Name="ApiKey" Grid.Row="4" Grid.Column="1"/><TextBlock Grid.Row="5" Text="调度策略" VerticalAlignment="Center"/><ComboBox Name="Routing" Grid.Row="5" Grid.Column="1" SelectedIndex="0"><ComboBoxItem Content="均衡分派"/><ComboBoxItem Content="质量优先"/><ComboBoxItem Content="速度优先"/></ComboBox><StackPanel Grid.Row="6" Grid.ColumnSpan="2"><TextBlock Text="密钥只保存在程序内存中，关闭应用即清除。生产版将由后端密钥管理服务处理。" Foreground="#637181" Margin="0,16,0,8"/><Button Name="SaveConfig" Content="保存本次运行配置" Background="#1269C7" Foreground="White" Padding="14,8" HorizontalAlignment="Right"/></StackPanel></Grid></Border></Grid>
   <Grid Name="SkillsPage" Visibility="Collapsed"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/></Grid.RowDefinitions><StackPanel><TextBlock Text="Skill System" Foreground="#0C827A" FontSize="12"/><TextBlock Text="Agent 技能中心" FontSize="26" FontWeight="Bold" Foreground="#17212B"/></StackPanel><TextBlock Grid.Row="1" Text="指挥 Agent 负责拆解和路由；每个专业 Agent 只能使用已启用的专属技能。" Foreground="#637181" Margin="0,14,0,14"/><ScrollViewer Grid.Row="2" VerticalScrollBarVisibility="Auto"><WrapPanel Name="SkillsPanel"/></ScrollViewer></Grid>
  </Grid></Grid>
</Window>
'@
$reader = [System.Xml.XmlNodeReader]::new($xaml); $window = [Windows.Markup.XamlReader]::Load($reader)
function C($name) { $window.FindName($name) }
$pages = @('ProjectsPage','OrchestratorPage','SettingsPage','SkillsPage')
function Show-Page($page) { foreach($item in $pages) { (C $item).Visibility = if($item -eq $page) { 'Visible' } else { 'Collapsed' } }; if($page -eq 'ProjectsPage'){ Refresh-Tasks }; if($page -eq 'OrchestratorPage'){ Refresh-Orchestrator } }
function Save-Tasks { New-Item -ItemType Directory -Force $dataDirectory | Out-Null; $script:tasks | ConvertTo-Json -Depth 3 | Set-Content $dataFile -Encoding UTF8 }
function Refresh-Tasks { $todo=(C 'TodoList'); $progress=(C 'ProgressList'); $done=(C 'DoneList'); $todo.ItemsSource=@($script:tasks | Where-Object Status -eq '待处理'); $progress.ItemsSource=@($script:tasks | Where-Object Status -eq '进行中'); $done.ItemsSource=@($script:tasks | Where-Object Status -eq '已完成'); (C 'Metrics').Text="待处理 $($todo.Items.Count)  |  进行中 $($progress.Items.Count)  |  已完成 $($done.Items.Count)  |  总任务 $($script:tasks.Count)" }
function Refresh-Orchestrator { (C 'QueueList').ItemsSource=@($script:tasks | Where-Object Status -ne '已完成'); $active=@($script:tasks | Where-Object Status -eq '进行中' | ForEach-Object Agent); (C 'AgentList').ItemsSource=@($script:agents | ForEach-Object { "$_  -  $(if($_ -in $active){'执行中'}else{'可调度'})" }); (C 'EventList').ItemsSource=@($script:events | Select-Object -First 6) }
function Move-Selected($source, $newStatus) { $task=(C $source).SelectedItem; if($null -eq $task){ [System.Windows.MessageBox]::Show('请先选择一项任务。','AI Software Team'); return }; $task.Status=$newStatus; $script:events.Insert(0,"$($task.Agent) 的任务 [$($task.Title)] 已移至$newStatus"); Save-Tasks; Refresh-Tasks }
(C 'ProjectsNav').Add_Click({ Show-Page 'ProjectsPage' }); (C 'OrchestratorNav').Add_Click({ Show-Page 'OrchestratorPage' }); (C 'SettingsNav').Add_Click({ Show-Page 'SettingsPage' }); (C 'SkillsNav').Add_Click({ Show-Page 'SkillsPage' })
(C 'ProgressBack').Add_Click({ Move-Selected 'ProgressList' '待处理' }); (C 'ProgressNext').Add_Click({ Move-Selected 'ProgressList' '已完成' }); (C 'DoneBack').Add_Click({ Move-Selected 'DoneList' '进行中' })
(C 'RunQueue').Add_Click({ $next=$script:tasks | Where-Object Status -eq '待处理' | Select-Object -First 1; if($null -eq $next){ [System.Windows.MessageBox]::Show('没有待处理任务。','智能调度中心') }else{ $next.Status='进行中'; $script:events.Insert(0,"指挥 Agent 已将 [$($next.Title)] 分派给 $($next.Agent)"); Save-Tasks; Refresh-Orchestrator; Refresh-Tasks } })
(C 'SaveConfig').Add_Click({ $script:sessionApiKey=(C 'ApiKey').Password; $script:events.Insert(0,"指挥 Agent 已采用 $((C 'ModelName').Text) 的模型配置"); [System.Windows.MessageBox]::Show('连接配置已应用于当前运行会话。API Key 不会写入磁盘。','模型与 API') })
(C 'NewTask').Add_Click({ $dialog=New-Object Windows.Window -Property @{Title='新建任务';Width=430;Height=360;WindowStartupLocation='CenterOwner';Owner=$window}; $panel=New-Object Windows.Controls.StackPanel -Property @{Margin='22'}; $dialog.Content=$panel; $title=New-Object Windows.Controls.TextBox; $agent=New-Object Windows.Controls.ComboBox; $script:agents | ForEach-Object { [void]$agent.Items.Add($_) }; $agent.SelectedIndex=0; $priority=New-Object Windows.Controls.ComboBox; '高','中','低' | ForEach-Object { [void]$priority.Items.Add($_) }; $priority.SelectedIndex=1; foreach($pair in @(@('任务名称',$title),@('负责 Agent',$agent),@('优先级',$priority))){ $panel.Children.Add((New-Object Windows.Controls.TextBlock -Property @{Text=$pair[0];Margin='0,7,0,3'})); $panel.Children.Add($pair[1]) }; $create=New-Object Windows.Controls.Button -Property @{Content='创建任务';Margin='0,20,0,0';HorizontalAlignment='Right';Padding='14,7'}; $create.Add_Click({if([string]::IsNullOrWhiteSpace($title.Text)){return}; [void]$script:tasks.Insert(0,(New-TaskItem $title.Text $agent.SelectedItem $priority.SelectedItem '待处理' '')); $script:events.Insert(0,"指挥 Agent 已接收新任务 [$($title.Text)]"); Save-Tasks; Refresh-Tasks; $dialog.Close()}); $panel.Children.Add($create); $dialog.ShowDialog() | Out-Null })
foreach($entry in $script:skills.GetEnumerator()){ $card=New-Object Windows.Controls.Border -Property @{Background='White';BorderBrush='#D8E0E5';BorderThickness='1';Padding='14';Margin='0,0,12,12';Width=420}; $stack=New-Object Windows.Controls.StackPanel; $stack.Children.Add((New-Object Windows.Controls.TextBlock -Property @{Text=$entry.Key;FontWeight='Bold';FontSize=14;Margin='0,0,0,8'})); foreach($skill in $entry.Value){ $stack.Children.Add((New-Object Windows.Controls.CheckBox -Property @{Content=$skill;IsChecked=$true;Margin='0,3'})) }; $card.Child=$stack; (C 'SkillsPanel').Children.Add($card) }
Refresh-Tasks; Refresh-Orchestrator; $window.ShowDialog() | Out-Null


