const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", Object.freeze({
  isElectron: true,
  getAppInfo: () => ipcRenderer.invoke("app:get-info"),
  configureModel: (config) => ipcRenderer.invoke("model:configure", config),
  clearModel: () => ipcRenderer.invoke("model:clear"),
  getModelStatus: () => ipcRenderer.invoke("model:status"),
  testModel: () => ipcRenderer.invoke("model:test"),
  testModelConfig: (config) => ipcRenderer.invoke("model:test-config", config),
  getModelPool: () => ipcRenderer.invoke("model-pool:get"),
  saveModelProfile: (profile) => ipcRenderer.invoke("model-pool:save-profile", profile),
  deleteModelProfile: (profileId) => ipcRenderer.invoke("model-pool:delete-profile", profileId),
  assignModelProfile: (target, profileId) => ipcRenderer.invoke("model-pool:assign", target, profileId),
  testModelProfile: (profileId) => ipcRenderer.invoke("model-pool:test-profile", profileId),
  getMediaModels: () => ipcRenderer.invoke("media-model:get"),
  configureMediaModel: (kind, payload) => ipcRenderer.invoke("media-model:configure", kind, payload),
  clearMediaModel: (kind) => ipcRenderer.invoke("media-model:clear", kind),
  exportAudit: (payload) => ipcRenderer.invoke("audit:export", payload),
  executeAgentTask: (payload) => ipcRenderer.invoke("agent:execute", payload),
  chat: (payload) => ipcRenderer.invoke("agent:chat", payload),
  getComputerAccess: () => ipcRenderer.invoke("computer-access:status"),
  setComputerAccess: (enabled) => ipcRenderer.invoke("computer-access:set", enabled),
  getPlugins: () => ipcRenderer.invoke("plugins:get"),
  setPluginEnabled: (pluginId, enabled) => ipcRenderer.invoke("plugins:set-enabled", pluginId, enabled),
  importPlugin: () => ipcRenderer.invoke("plugins:import"),
  importPluginDirectory: () => ipcRenderer.invoke("plugins:import-directory"),
  openPluginDirectory: () => ipcRenderer.invoke("plugins:open-directory"),
  getMemoryGraph: () => ipcRenderer.invoke("memory-graph:get"),
  searchMemoryGraph: (query, limit) => ipcRenderer.invoke("memory-graph:search", query, limit),
  chooseMemoryGraphFolder: () => ipcRenderer.invoke("memory-graph:choose-folder"),
  reindexMemoryGraph: () => ipcRenderer.invoke("memory-graph:reindex"),
  clearMemoryGraph: () => ipcRenderer.invoke("memory-graph:clear"),
  openMemoryGraphFolder: () => ipcRenderer.invoke("memory-graph:open-folder"),
  getKnowledgeDocuments: () => ipcRenderer.invoke("knowledge:get"),
  importKnowledgeDocuments: () => ipcRenderer.invoke("knowledge:import"),
  migrateKnowledgeDocuments: (documents) => ipcRenderer.invoke("knowledge:migrate", documents),
  deleteKnowledgeDocument: (id) => ipcRenderer.invoke("knowledge:delete", id),
  openKnowledgeDocument: (id) => ipcRenderer.invoke("knowledge:open", id),
  onMemoryGraphProgress: (listener) => {
    const handler = (_event, progress) => listener(progress);
    ipcRenderer.on("memory-graph:progress", handler);
    return () => ipcRenderer.removeListener("memory-graph:progress", handler);
  },
  getVoiceSettings: () => ipcRenderer.invoke("voice:get"),
  configureVoice: (payload) => ipcRenderer.invoke("voice:configure", payload),
  clearVoice: () => ipcRenderer.invoke("voice:clear"),
  testVoice: () => ipcRenderer.invoke("voice:test"),
  transcribeVoice: (payload) => ipcRenderer.invoke("voice:transcribe", payload),
  synthesizeVoice: (payload) => ipcRenderer.invoke("voice:synthesize", payload),
  executeMediaWorkflow: (kind, payload) => ipcRenderer.invoke("media:execute-workflow", kind, payload),
  openMediaOutput: (filePath) => ipcRenderer.invoke("media:open-output", filePath),
  getConfigurationVault: () => ipcRenderer.invoke("config-vault:status"),
  openConfigurationVault: () => ipcRenderer.invoke("config-vault:open"),
  exportConfigurationVault: () => ipcRenderer.invoke("config-vault:export"),
  importConfigurationVault: () => ipcRenderer.invoke("config-vault:import"),
  relaunchApp: () => ipcRenderer.invoke("app:relaunch"),
  getSandboxStatus: () => ipcRenderer.invoke("sandbox:status"),
  verifyTaskProject: (taskId) => ipcRenderer.invoke("sandbox:verify", taskId),
  getTaskGitStatus: (taskId) => ipcRenderer.invoke("sandbox:git-status", taskId),
  createTaskGitSnapshot: (taskId, message) => ipcRenderer.invoke("sandbox:git-snapshot", taskId, message),
  openTaskProject: (taskId) => ipcRenderer.invoke("sandbox:open", taskId),
  getWorkspace: () => ipcRenderer.invoke("workspace:get"),
  setWorkspace: (selectedPath) => ipcRenderer.invoke("workspace:set", selectedPath),
  chooseWorkspace: () => ipcRenderer.invoke("workspace:choose"),
  inspectDelivery: () => ipcRenderer.invoke("delivery:inspect"),
  createDeliveryRelease: (payload) => ipcRenderer.invoke("delivery:create", payload),
  openDeliveryPath: (selectedPath) => ipcRenderer.invoke("delivery:open", selectedPath),
  configureIntegrations: (payload) => ipcRenderer.invoke("integration:configure", payload),
  clearIntegrations: () => ipcRenderer.invoke("integration:clear"),
  getIntegrationStatus: () => ipcRenderer.invoke("integration:status"),
  testIntegration: () => ipcRenderer.invoke("integration:test"),
  fetchDocument: (url) => ipcRenderer.invoke("integration:fetch-document", url),
  inspectRepository: (repository) => ipcRenderer.invoke("integration:inspect-repository", repository),
  openExternal: (url) => ipcRenderer.invoke("integration:open-external", url),
  getUpdateStatus: () => ipcRenderer.invoke("update:status"),
  setUpdateSettings: (settings) => ipcRenderer.invoke("update:settings", settings),
  checkForUpdates: () => ipcRenderer.invoke("update:check"),
  downloadUpdate: () => ipcRenderer.invoke("update:download"),
  restartToUpdate: () => ipcRenderer.invoke("update:restart"),
  onUpdateState: (listener) => {
    const handler = (_event, state) => listener(state);
    ipcRenderer.on("update:state", handler);
    return () => ipcRenderer.removeListener("update:state", handler);
  }
}));
