const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", Object.freeze({
  isElectron: true,
  getAppInfo: () => ipcRenderer.invoke("app:get-info"),
  configureModel: (config) => ipcRenderer.invoke("model:configure", config),
  clearModel: () => ipcRenderer.invoke("model:clear"),
  getModelStatus: () => ipcRenderer.invoke("model:status"),
  testModel: () => ipcRenderer.invoke("model:test"),
  getModelPool: () => ipcRenderer.invoke("model-pool:get"),
  saveModelProfile: (profile) => ipcRenderer.invoke("model-pool:save-profile", profile),
  deleteModelProfile: (profileId) => ipcRenderer.invoke("model-pool:delete-profile", profileId),
  assignModelProfile: (target, profileId) => ipcRenderer.invoke("model-pool:assign", target, profileId),
  testModelProfile: (profileId) => ipcRenderer.invoke("model-pool:test-profile", profileId),
  exportAudit: (payload) => ipcRenderer.invoke("audit:export", payload),
  executeAgentTask: (payload) => ipcRenderer.invoke("agent:execute", payload),
  chat: (payload) => ipcRenderer.invoke("agent:chat", payload),
  getPlugins: () => ipcRenderer.invoke("plugins:get"),
  setPluginEnabled: (pluginId, enabled) => ipcRenderer.invoke("plugins:set-enabled", pluginId, enabled),
  openPluginDirectory: () => ipcRenderer.invoke("plugins:open-directory"),
  getSandboxStatus: () => ipcRenderer.invoke("sandbox:status"),
  verifyTaskProject: (taskId) => ipcRenderer.invoke("sandbox:verify", taskId),
  getTaskGitStatus: (taskId) => ipcRenderer.invoke("sandbox:git-status", taskId),
  createTaskGitSnapshot: (taskId, message) => ipcRenderer.invoke("sandbox:git-snapshot", taskId, message),
  openTaskProject: (taskId) => ipcRenderer.invoke("sandbox:open", taskId),
  getWorkspace: () => ipcRenderer.invoke("workspace:get"),
  setWorkspace: (selectedPath) => ipcRenderer.invoke("workspace:set", selectedPath),
  chooseWorkspace: () => ipcRenderer.invoke("workspace:choose"),
  inspectDelivery: () => ipcRenderer.invoke("delivery:inspect"),
  createDeliveryRelease: (payload) => ipcRenderer.invoke("delivery:create", payload),
  openDeliveryPath: (selectedPath) => ipcRenderer.invoke("delivery:open", selectedPath),
  configureIntegrations: (payload) => ipcRenderer.invoke("integration:configure", payload),
  clearIntegrations: () => ipcRenderer.invoke("integration:clear"),
  getIntegrationStatus: () => ipcRenderer.invoke("integration:status"),
  fetchDocument: (url) => ipcRenderer.invoke("integration:fetch-document", url),
  inspectRepository: (repository) => ipcRenderer.invoke("integration:inspect-repository", repository)
}));
